# Schema for the configuration files of the Netcall AI Widget module.
localgov_netcall_ai_widget.settings:
  type: config_object
  label: 'Netcall AI Widget settings'
  mapping:
    workspace_id:
      type: text
      label: 'Workspace ID'
    partition_id:
      type: text
      label: 'Partition ID'
    partition_overrides:
      type: text
      label: 'Partition Overrides'


